export const TV_SERIES = [
  {
    name: 'The Terror',
    genres: ['horror', 'drama', 'dark comedy'],
    season: 3,
    network: ['AMC'],
    premiere: '20.10.2019',
  },
  {
    name: 'Better Call Saul',
    genres: ['crime', 'tradegy'],
    season: 4,
    network: ['AMC', 'Netflix'],
    premiere: '05.11.2019',
  },
  {
    name: 'Preacher',
    genres: ['drama', 'dark comedy'],
    season: 5,
    network: ['AMC'],
    premiere: '01.01.2019',
  },
  {
    name: 'The Terror',
    genres: ['horror', 'drama'],
    season: 3,
    network: ['AMC'],
    premiere: '20.10.2019',
  },
  {
    name: 'The Terror',
    genres: ['horror', 'drama'],
    season: 3,
    network: ['AMC'],
    premiere: '20.10.2019',
  },
  {
    name: 'The Terror',
    genres: ['horror', 'drama'],
    season: 3,
    network: ['AMC'],
    premiere: '20.10.2019',
  },
  {
    name: 'Preacher',
    genres: ['drama', 'dark comedy'],
    season: 5,
    network: ['AMC'],
    premiere: '01.01.2019',
  },
  {
    name: 'Preacher',
    genres: ['drama', 'dark comedy'],
    season: 5,
    network: ['AMC'],
    premiere: '01.01.2019',
  },
  {
    name: 'The Terror',
    genres: ['horror', 'drama'],
    season: 3,
    network: ['AMC'],
    premiere: '20.10.2019',
  },
  {
    name: 'Better Call Saul',
    genres: ['crime', 'tradegy'],
    season: 4,
    network: ['AMC', 'Netflix'],
    premiere: '05.11.2019',
  },
  {
    name: 'Preacher',
    genres: ['drama', 'dark comedy'],
    season: 5,
    network: ['AMC'],
    premiere: '01.01.2019',
  },
  {
    name: 'The Terror',
    genres: ['horror', 'drama'],
    season: 3,
    network: ['AMC'],
    premiere: '20.10.2019',
  },
  {
    name: 'Better Call Saul',
    genres: ['crime', 'tradegy'],
    season: 4,
    network: ['AMC', 'Netflix'],
    premiere: '05.11.2019',
  },
  {
    name: 'Preacher',
    genres: ['drama', 'dark comedy'],
    season: 5,
    network: ['AMC'],
    premiere: '01.01.2019',
  },
];
